name: wcmcs_mobile
description: "Water Consumption Monitoring Control System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  url_launcher: ^6.3.0
  intl: ^0.19.0
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_svg: ^2.0.10

  # dotted
  dotted_border: ^2.1.0

  #for charts
  syncfusion_flutter_charts: ^25.2.7
  # for scrolling rows and columns
  flextras: ^1.0.0
  gap: ^3.0.1
  restart_app: ^1.2.1
  responsive_sizer: ^3.3.1
  
  # Firebase
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

  # calendar
  easy_date_timeline: ^1.1.3

  # dio
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/