name: wcmcs_mobile
description: "Water Consumption Monitoring Control System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.1.3
  url_launcher: ^6.2.6
  intl: ^0.19.0
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_svg: ^2.0.10+1
  #for charts
  syncfusion_flutter_charts: ^25.2.6
  # for scrolling rows and columns
  flextras: ^1.0.0
  gap: ^3.0.1
  restart_app: ^1.2.1
  responsive_sizer: ^3.3.1
  
  # Firebase
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  custom_lint: ^0.6.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/